// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbbiarbqsollvtaefbci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiYmlhcmJxc29sbHZ0YWVmYmNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MDA3NDQsImV4cCI6MjA1MzM3Njc0NH0.i-1G7SF9BW_9vZ9_9eRQSsk8OM_a829C6_xGLYORTLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);